### ISSUE TITLE
EPIC: As e-mobility providers we want to start sharing our data through the open standard OCPI, so to not have to mantain the custom API defined with NOI years ago

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/opendatahub-collectors#5]
The first e-mobility providers that have shared an OCPI end-points are Neogy and Driwe.

Reference specifications for the implementation of an OCPI-compliant Data Collector are provided in the specification document below.

Details of the connection end-points are available and will be documented / provided separately.

Tasks to be foreseen:

- [x] Test connections (in relation to the modules that are interesting for us, see available specification module) and share example response data
- [x] Specification documents for Neogy and Driwe, prepared by @rcavaliere -> [241004_SpecificheIntegrazione_NeogyOCPI_NOI_v1.1.pdf](https://github.com/user-attachments/files/17253512/241004_SpecificheIntegrazione_NeogyOCPI_NOI_v1.1.pdf)

- [ ] Data Collector implementation - probably we need a single OCPI-compliant module that manages the connection with all external data sources?

[230308_OCPIProfileSouthTyrol_NOI.pdf](https://github.com/user-attachments/files/16387380/230308_OCPIProfileSouthTyrol_NOI.pdf)

**Comment by rcavaliere** [comment]
@clezag wonderful! Completed the check of Neogy, works perfectly. Now we have to manage with the Data Provider the provision of the productive end-point, since this is just a demo OCPI end-point what we have... I will then check Driwe as well.

**Comment by clezag** [comment]
Just updating with what was exchanged via email:
Chargeup does not support us polling the `locations` endpoint every 5 minutes.

We will get all locations about once a day for the station details and states.

In addition, we need to supply a "eMSP" type endpoint where they can push state changes of single stations.
[Documentation here, 8.2.2](https://github.com/ocpi/ocpi/blob/master/releases/OCPI-2.2.pdf)
We'll try to just implement the PATCH requests of station states, which will be translated into measurements.
For authentication, we will exchange a random string "token C", which the endpoint checks.

**Comment by clezag** [comment]
@rcavaliere I've set up a POC of the OCPI EVSE receiver interface and sent you the connection details via mail

**Comment by clezag** [comment]
We're received positive feedback from Chargeup, the POC does work, now i'll implement it as a full data collector

**Comment by clezag** [comment]
@rcavaliere I've put up a fairly complete implementation in testing, data is visible in analytics, too:

https://mobility.api.opendatahub.testingmachine.eu/v2/tree/EChargingStation/*/latest?where=sorigin.eq.Neogy
with respective `sorigin` `Neogy` and `DRIWE-OCPI`

- have not checked if the station num-available is always correct (in theory I sum it up on every plug update)
- some metadata fields are questionable:
   - removed the `plug.connectors.last_updated` field, because it would just update the metadata object often.   
   - `plug.connectors.tarrif_ids`  I think is fairly useless because the user cannot access the tarrifs and the ID by itself is just some string
   - `station.publish` is always `true`, according to the spec document, so why include it?
- maybe we should add a prefix (origin?) to every scode, to avoid overlaps, they are just random IDs, that I assume are not global

It's set up in a way that driwe and neogy have separate endpoints, currently driwe polls every 10 minutes, neogy every 4h, and gets status updates via push.
In theory we are ready for driwe pushes too, we just have to communicate the endpoint, if they are able to push.

**Comment by rcavaliere** [comment]
@clezag thanks for your work, I will test this carefully in the next days in order to give you feedback and decide how to manage these points.

**Comment by rcavaliere** [comment]
@clezag here my feedback after some more detailed analysis:

- I checked the correspondence between plugs and stations, the count seems OK (just made some examples)
- I agree to not store as METADATA the fields you mentioned, they do not add nothing
- yes, the values of `stationcode` could not be unique, let's consider the concatenation of the value in origin (i.e. `origin_stationcode`) as value to be stored here

Once you fix this, I think we can go in production with the Data Collector of Neogy. Next week let's try to complete also Driwe end-point

**Comment by rcavaliere** [comment]
@clezag just one more thing, can you log if we are receiving real-time updates with this push mechanism? I would like to be share that also this part is properly configured on their side.

**Comment by clezag** [comment]
> [@clezag](https://github.com/clezag) just one more thing, can you log if we are receiving real-time updates with this push mechanism? I would like to be share that also this part is properly configured on their side.

Yes, this is all on the new infrastructure, so we have the raw data. We are already receiving push updates with quite a high frequency.

I'll implement the last batch of changes within this week, they should be quick fixes

**Comment by clezag** [comment]
@rcavaliere I've cleaned up the old testing data and done a fresh import. 
Once you give the go ahead, we can go into production.

There are a few details which we have not discussed, I'll mention them for completeness sake, and if we want to tackle these in the future:

## inactive stations
In contrast to the previous data collector, now there is no mechanism that sets stations inactive. 
This is because the transformer never gets the complete set of locations, only partial lists (because of paging), so it doesn't know when a station is missing in the list. 

It would be technically possible to implement this , but for now I'll leave it as is, once we get to the point where stations have to be pruned, we have a better idea about how the data patterns look like, and maybe there is a simple way to add it.

## update frequency
The way push notifications work, we only get state CHANGES, which means that if a station is not used for 3 hours, there will be no new data point for 3 hours.

BUT: The regular station polling full update always writes the current state. 

e.g. for neogy, we poll every 4 hours, so at minimum there is one data point every 4 hours.

DRIWE polls every 10 minutes, so there is a data point at least every 10 minutes.

That's why the data update patterns will be a bit strange, a mix between random updates and periodic.

We could do this in another way: 
OCPI messages always have a `last_updated` field. Currently, I'm not using this as measurement timestamp, but the time when the message arrives at the endpoint. 
If we used the `last_updated` as measurement timestamp instead, we would not have the strange mix I explained above.
The downside would be that if there is no update for a long time, there will not be a measurement, and data might look out of date, even though it's correct.

**Comment by rcavaliere** [comment]
@clezag I think we are ready to go to production with Neogy (for Driwe, let me check this more in detail first, I didn't do this yet). Regarding the points of your last post:

- inactive stations: I would leave this as such, I would leave to 3rd parties / front-end applications the work to understand how to distinguish this based on the last timestamp available
- update frequency: I am in favor to consider the timestamp of the last push notification (change of status) or our periodic polling action, not nothing else, as it should be implemented now. Let's avoid other strategies...

So, let's go in production with Neogy, let me know when you have done this!

**Comment by clezag** [comment]
@rcavaliere It's now up in production, I've contacted the data provider to switch over the push updates, too. Currently it's only polling every 4 hours.

Should I set all the old `origin=ALPERIA` stations inactive?

**Comment by rcavaliere** [comment]
@clezag good point. I suggest to first put completely in production Neogy Data Collector, than we switch off the Data Collector Alperia. It's important that stations of Alperia remain available over the API, but set as inactive

**Comment by clezag** [comment]
@rcavaliere 
The data provider has switched over to production and we're getting the push messages.

I've set all the alperia stations inactive in testing:
```sql
update station set active=false where stationtype in ('EChargingStation','EChargingPlug') and origin = 'ALPERIA'
```

On analytics they are still visible, because it does not filter for active=true

If you confirm, I will do the same in production.

**Comment by rcavaliere** [comment]
@clezag thanks for the excellent work here!!! Yes please, change this also in production

**Comment by clezag** [comment]
@rcavaliere ok done, now waiting for news on DRIWE.

**Comment by rcavaliere** [comment]
@clezag I checked the DRIWE implementation, it looks everything OK. How is currently the implementation here? Do we get push from them or we just make a pull? So that we can finalize also this integration in cooperation with them.

**Comment by rcavaliere** [comment]
@clezag let me talk to DRIWE, so that we can first implement the final solution, test and then deploy it.

**Comment by rcavaliere** [comment]
@clezag thanks for the update. Maybe it could be a good strategy to set a different origin and to put the old Data Collector on-hold? For the records provided: the end-point is productive, but currently is limited to the stations in South Tyrol. I am discussing with DRIWE to provide all stations that they have.

**Comment by clezag** [comment]
@rcavaliere Sure, what origin should I set it to?

**Comment by rcavaliere** [comment]
@clezag for example DRIWE-OCPI?

**Comment by clezag** [comment]
@rcavaliere Done.

I've left the old data collector (without the transformer) running, so we still have the raw data from the old data collector in case we want to load it.
